### ISSUE TITLE
webpack4.1.1-error

### ISSUE THREAD

**Issue by holdfuture** [SimenB/add-asset-html-webpack-plugin#104]
plugin could not registered at "html-webpack-plugin-before-html-generation". Hook was not found

**Comment by SimenB** [comment]
Have you upgraded to 2.1.3 which adds support for webpack 4? If yes, can you provide a repro showing the error?

**Comment by holdfuture** [comment]
yes,i have upgraded to 2.1.3.
![qq 20180315083749](https://user-images.githubusercontent.com/17507765/37438181-eaba3632-282b-11e8-8389-77cffe074da5.png)

**Comment by SimenB** [comment]
I think you've run into the issue addressed by cf3fa7f9ab980c901032966f33adfc4bdb3ede9c. Is your configuration in the correct order?

**Comment by holdfuture** [comment]
thanks，I fix it

**Comment by holdfuture** [comment]
thanks，It works

**Comment by holdfuture** [comment]
thanks a lot， It works

**Comment by SimenB** [comment]
Great!
