### ISSUE TITLE
Wildcard paths no longer working from v2.1.3

### ISSUE THREAD

**Issue by mythz** [SimenB/add-asset-html-webpack-plugin#108]
Hi, this used to work in v2.1.2:

```js
new AddAssetHtmlPlugin({ filepath: path.join(__dirname, 'wwwroot/dist/*.dll.js') })
```

But fails after upgrading to v2.1.3:

    ERROR in   Error: ENOENT: no such file or directory, stat 'C:\src\MyApp\wwwroot\dist\*.dll.js'

I'm using webpack 3.11.0. I've reverted to v2.1.2 to resolve the issue, please let me know if there's anything you need.

**Comment by mythz** [comment]
It happened after trying to upgrade one of our empty templates, but just discovered the solution was to delete my `npm-shrinkwrap.json` and `node_modules` then re-install so must be due to one of the pinned deps.

A repro is from this commit: https://github.com/NetCoreTemplates/vuetify-spa/commit/cfe180f5c4c3b41b06311857384723deab7f4bf8

Then upgrade:

    npm i add-asset-html-webpack-plugin@latest

and try to run `dev` or `build`: 

This is resolved with the next commit which deleted the old npm-shrinkwrap.json and re-installing. https://github.com/NetCoreTemplates/vuetify-spa/commit/0fdde754baf7f58a1b4c27fc9187cceb1596b5a8

**Comment by SimenB** [comment]
Oh, that's interesting, I thought npm ironed out most of their hoisting bugs in version 5. Great that it worked out for you, though! 🙂
