### ISSUE TITLE
vendors is not defined

### ISSUE THREAD

**Issue by xiaopihaidenger** [SimenB/add-asset-html-webpack-plugin#116]
![image](https://user-images.githubusercontent.com/18025615/39853053-7e8d3ae2-5452-11e8-8d1c-c6238cf1e8ca.png)
![image](https://user-images.githubusercontent.com/18025615/39853069-94e6f47c-5452-11e8-897c-94c3584645e4.png)

**Comment by SimenB** [comment]
Hmm, I don't think I've encountered that one before. Are you able to set up a small reprodcution that I can pull down and see the error?

**Comment by xiaopihaidenger** [comment]
I've already solved it.thank you very mush.
![image](https://user-images.githubusercontent.com/18025615/39916864-603bfe42-553e-11e8-8994-db8b77c81e34.png)

**Comment by SimenB** [comment]
Great! 😀
