### ISSUE TITLE
Conflicting library with SRIPlugin

### ISSUE THREAD

**Issue by BartJanvanAssen** [SimenB/add-asset-html-webpack-plugin#119]
Hi All, 

I have some issues with webpack 4 + ICW SRI plugin i described the issue in this Issue:
https://github.com/waysact/webpack-subresource-integrity/issues/75

It's conflicting with this lib, so maybe you guys have a clue whats going on here?

My debug repo is over here: with included full steps to reproduce in the readme
https://github.com/BartJanvanAssen/Issue-Webpack-SRIPlugin-and-AddAsset

**Comment by jscheid** [comment]
Hi guys, I'm pretty sure this is on your side. I think this: https://github.com/SimenB/add-asset-html-webpack-plugin/blob/cf3fa7f9ab980c901032966f33adfc4bdb3ede9c/src/index.js#L13-L14
... should never return a promise, it should call the callback instead.

Also I think you need to use something like 
```js
compilation.hooks.htmlWebpackPluginAfterHtmlProcessing.tapAsync(
```

for `callback` to be there.

I know that it's some kind of compatibility layer that you're using here, but it doesn't seem to be working in this case.

**Comment by SimenB** [comment]
Hiya, sorry about the slow response.

Are you saying just removing the implicit `return` is enough? If so, PR very much welcome! :)

**Comment by SimenB** [comment]
I'll probably just merge #99 and drop webpack 3

**Comment by BartJanvanAssen** [comment]
Sounds good! Really looking forward to your change

**Comment by BartJanvanAssen** [comment]
debugged / tried to get something up and running... Note: outside of the test project

This works a bit better.  However if i use this, it gets me an error me an error in the bundle.js that "vendor" is not an var in the bundle.js. so somehow somewhere in the plugin itself, there's something else thats not working as it should be. i think the contents gets not added or something.. 
The build is not crashing anymore so we're half way :)


My additions:
![image](https://user-images.githubusercontent.com/4742816/40622837-c99c9b5e-62a3-11e8-8a81-a36f6bc18ac1.png)

Remaining error:
![image](https://user-images.githubusercontent.com/4742816/40622969-8c7f31d6-62a4-11e8-9ae8-4b4013dc8eab.png)
addition:  i see no vendor file being added in the HTML

**Comment by BartJanvanAssen** [comment]
This morning i tried it out with the next branch version 3.0.x and thats working 👍

**Comment by SimenB** [comment]
That's great! It should be published under the `next` tag

**Comment by SimenB** [comment]
Released as `latest` now, sorry about the delay
