### ISSUE TITLE
Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [SimenB/add-asset-html-webpack-plugin#141]
node_modules/add-asset-html-webpack-plugin/lib/index.js:104
    compiler.hooks.compilation.tap('AddAssetHtmlPlugin', compilation => {
                   ^
TypeError: Cannot read property 'compilation' of undefined

**Comment by SimenB** [comment]
Can you set up a reproduction showing the error?

Version of webpack, html-webpack-plugin and your webpack config at least is necessary

**Comment by HiZhaoxiaoyang** [comment]
here's my package.json:
`{
  "name": "Test",
  "version": "1.0.0",
  "license": "MIT",
  "description": "test",
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "build": "node build/build.js",
    "build:dll": "webpack -p --config build/webpack.dll.conf.js",
  },
  "dependencies": {
    "add-asset-html-webpack-plugin": "^3.1.1",
    "babel-polyfill": "^6.26.0",
    "file-saver": "^1.3.8",
    "happypack": "^5.0.0",
    "nprogress": "0.2.0",
    "script-loader": "^0.7.2",
    "vue": "2.5.10",
    "vue-concise-slider": "^2.4.8",
    "vue-count-to": "^1.0.13",
    "vue-infinite-scroll": "^2.0.2",
    "vue-router": "3.0.1",
    "vuex": "3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "7.2.3",
    "babel-core": "6.26.0",
    "babel-eslint": "8.0.3",
    "babel-helper-vue-jsx-merge-props": "2.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-syntax-jsx": "6.18.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-plugin-transform-vue-jsx": "3.5.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-stage-2": "6.24.1",
    "chalk": "2.3.0",
    "copy-webpack-plugin": "4.2.3",
    "eslint": "4.13.1",
    "eslint-friendly-formatter": "3.0.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-html": "4.0.1",
    "eventsource-polyfill": "0.9.6",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "friendly-errors-webpack-plugin": "1.6.1",
    "node-notifier": "5.1.2",
    "optimize-css-assets-webpack-plugin": "3.2.0",
    "ora": "1.3.0",
    "portfinder": "1.0.13",
    "rimraf": "2.6.2",
    "semver": "5.4.1",
    "uglifyjs-webpack-plugin": "1.1.3",
    "url-loader": "0.6.2",
    "vue-loader": "13.5.0",
    "vue-style-loader": "3.0.3",
    "vue-template-compiler": "2.5.10",
    "html-webpack-plugin": "2.30.1",
    "webpack": "3.10.0",
    "webpack-bundle-analyzer": "2.9.1",
    "webpack-dev-server": "2.9.7",
    "webpack-merge": "4.1.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
`

1. add webpack.dll.conf.js to build folder and run 'yarn run build:dll' will generate a manifest.json file:
`
const path = require('path')
const webpack = require('webpack')
module.exports = {
  entry: {
    vendor: [
    'vue/dist/vue.esm.js',
    'vue-router',
    'vuex',
    'babel-polyfill'
    ]
  },
  output: {
    path: path.join(__dirname, '../static/js'),
    filename: '[name].dll.js',
    library: '[name]_library'
  },
  plugins: [
    new webpack.DllPlugin({
      path: path.join(__dirname, '.', '[name]-manifest.json'),
      name: '[name]_library'
    }),  
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        drop_console:true,
        drop_debugger:true
      },
      output:{
        comments: false
      },
      sourceMap: true
    })
  ]
}
`
2. add 'add-asset-html-webpack-plugin' to webpackConfig.plugins:
`
const AddAssetHtmlPlugin = require('add-asset-html-webpack-plugin')
//plugins: 
[new webpack.DllReferencePlugin({
        // manifest
        context: path.join(__dirname),
        manifest: require("./vendor-manifest.json")
        // name: "./my-dll.js",
        // scope: "xyz",
        // sourceType: "commonjs2"
    }),
    new AddAssetHtmlPlugin([{
        filepath: path.resolve(__dirname, '../dist/static/js/vendor.dll.js'),
        attributes: {
            nomodule: true
        }
        // outputPath: utils.assetsPath('js'),
        // publicPath: path.posix.join(config.build.assetsPublicPath, 'static/js'),
        // includeSourcemap: false,
        // hash: true
    }])]
`
2. run `yarn run build`, console will output errors as mentioned:

> bash-3.2# yarn run build
yarn run v1.10.1
$ node build/build.js
⠋ building for production...err: null
rm: 28.213ms
Error: TypeError: Cannot read property 'hooks' of undefined
    at AddAssetHtmlPlugin.apply (/Users/myproject/node_modules/add-asset-html-webpack-plugin/lib/index.js:152:21)

3. and then I add a try-catch before 'compiler.hooks.compilation.tap('AddAssetHtmlPlugin' at 'node_modules/add-asset-html-webpack-plugin/lib/index.js:104' to let the build proceed.

finally it doesn't works~

thanks for your reply.

**Comment by SimenB** [comment]
Ah, you're using webpack 3. This plugin requires webpack 4. You can install version `2.1.3` if you cannot upgrade to Webpack 4.

Happy to reopen if I misunderstood!

**Comment by HiZhaoxiaoyang** [comment]
cool, thanks!
