### ISSUE TITLE
Incorrect generated file path when using add-assest-html-webpack-plugin

### ISSUE THREAD

**Issue by tjcchen** [SimenB/add-asset-html-webpack-plugin#183]
Hello,

This is my first use of `add-assest-html-webpack-plugin`. I want to add `*.dll.js` to my project and did what the README.md instructed. But the there is something wrong with the generated file path. like:

> /webpack-studio/dll-config/dist/auto/library.dll.js

the `/dist/auto/` path is not expected. I didn't see too much documentations to elaborate this portion. Could you please help to take a look?

Some code snippets like:

>new webpack.DllReferencePlugin({
>  context: path.join(__dirname),
>   manifest: require('./build/library-manifest.json')
>}),
>new HtmlWebpackPlugin({
>  template: path.join(__dirname, 'src/index.html'),
>  filename: 'index.html',
>  chunks: ['index'],
>  inject: true,
>  minify: {
>    html5: true,
>    collapseWhitespace: true,
>    preserveLineBreaks: false,
>    minifyCSS: true,
>    minifyJS: true,
>    removeComments: true
>  }
>}),
> new AddAssetHtmlPlugin({
>   filepath: path.resolve(__dirname, './build/library.dll.js'),
>   outputPath: '../build'
>})

Thanks in advance!

**Comment by silenceofWT** [comment]
There are no path errors if you use webpack4.x.This plugin is not compatible with webpack5.x.

**Comment by tjcchen** [comment]
Ok, many thanks for your reply! I'll try `add-assest-html-webpack-plugin` later again when I upgrade my project to webpack@5.x. Previously, I had fixed this problem with `html-webpack-tags-plugin`, even though the solution is not elegant.

Some of my code snippets look like this:
```
const HtmlWebpackTagsPlugin = require('html-webpack-tags-plugin');

...
new HtmlWebpackTagsPlugin({
  tags: [{
    path: '../build',  // specify your dll files folder path, this is important if your dll files are not within your /dist folder
    glob: 'library_*.dll.js',
    globPath: path.join(__dirname, './build')
  }],
  append: false
})
...

```

Hope our discussion can help other developers.

Cheers,

**Comment by tjcchen** [comment]
Closing this issue.

**Comment by edwardfhsiao** [comment]
html-webpack-tags-plugin works with webpack5
