### ISSUE TITLE
File is exported in wrong path with publicPath

### ISSUE THREAD

**Issue by zhbhun** [SimenB/add-asset-html-webpack-plugin#19]
If I defined `publicPath` for my DLL bundle, add-asset-html-webpack-plugin just copy DLL bundle into webpack.output.path other than `publicPath`.

**Comment by SimenB** [comment]
@zhbhun Do you have a reproducible example I could take a look at? 😄

**Comment by SimenB** [comment]
@zhbhun It might also be solved by #16

**Comment by SimenB** [comment]
@zhbhun could you try v1.0.0? With the `outputPath` option from #16.

**Comment by zhbhun** [comment]
Sorry, I don't mention my version of add-asset-html-webpack-plugin that is 0.4.0. New version has fixed it.

**Comment by SimenB** [comment]
Nah, the option is new, added after your issue. Just lucky timing 😄
