### ISSUE TITLE
AddAssetHtmlPlugin is not a function

### ISSUE THREAD

**Issue by zaaack** [SimenB/add-asset-html-webpack-plugin#20]
Hi~ This is a really useful plugin in packing dll file, thanks for your great work! But when I followed the steps in readme, I got an `AddAssetHtmlPlugin is not a function` error.

I looked up for a while, and found out the right way to import this plugin is

`const AddAssetHtmlPlugin  = require('add-asset-html-webpack-plugin').default`

if we don't use es6 and babel. 

Could you please add this to document or change the way of export?

**Comment by SimenB** [comment]
@zaaack Sorry about that, I messed it up when I added tests! Fixed in 1.0.1
