### ISSUE TITLE
JS Not included

### ISSUE THREAD

**Issue by pedrodcc** [SimenB/add-asset-html-webpack-plugin#23]
Hi,

I am generating a HTML and i want include one CSS and one JS but the JS is never included and i do not know why.

I have this configuration:

plugins: [
		new HtmlWebpackPlugin({
			title: 'Webpack demo',
			inject: false,
			template: require('html-webpack-template'),
			appMountId: 'app',
			cache: true
			//favicon
		}),
		new AddAssetHtmlPlugin(
			[{
				filename: require.resolve('./node_modules/jquery/dist/jquery.min.js'),
				typeOfAsset: 'js',
				includeSourcemap: false,
				hash: true
			},
			{
				filename: require.resolve('./src/assets/css/pgis.css'),
				typeOfAsset: 'css',
				includeSourcemap: false,
				hash: true
			}]
		),
		parts.gzip()
	],

The css file in included, only the js not. The path is correct and if i set an invalid directory i get an error.
Do you know how to debug that?

OS: OS X El Capitan

**Comment by SimenB** [comment]
First looks seems to indicate it's correct. Do you have a full sample I could debug?

**Comment by SimenB** [comment]
@pedrodcc ping

**Comment by SimenB** [comment]
Closing due to lack of response. Please ping me if you still have issues!
