### ISSUE TITLE
glob-parent unsafe

### ISSUE THREAD

**Issue by zjy01** [SimenB/add-asset-html-webpack-plugin#231]
`add-asset-html-webpack-plugin` has a deep dependencie with `glob-parent`
`glob-parent@3.1.0` is unsafe any more.
we need to upgrade it to `>= 5.1.2`
```bash
├─┬ add-asset-html-webpack-plugin@3.2.0
│ └─┬ globby@9.2.0
│   └─┬ fast-glob@2.2.7
│     └── glob-parent@3.1.0 
```

**Comment by monako97** [comment]
+1
