### ISSUE TITLE
html-weback-plugin  4.0.0-0 version is invalid

### ISSUE THREAD

**Issue by ThinkRealize** [SimenB/add-asset-html-webpack-plugin#253]
https://github.com/SimenB/add-asset-html-webpack-plugin/blob/018a89e9a5cfc1769a835ddb14a2045db5edfd05/package.json#L62

**Comment by SimenB** [comment]
It's not, what makes you think it is?

https://semver.npmjs.com/

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1404810/160158508-21a735cd-892d-44ab-87a6-c2565425e3c0.png">

**Comment by ThinkRealize** [comment]
I have html-webpack-plugin in my project，but npm install warn 

add-asset-html-webpack-plugin@5.0.1 requires a peer of html-webpack-plugin@^3.0.4 || ^4.0.0-0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/13347370/160321035-d0f62c37-6e06-4ca8-94ef-8244faab5eb2.png">

**Comment by SimenB** [comment]
`npm install --save-dev webpack html-webpack-plugin add-asset-html-webpack-plugin` works fine, and changing `html-weback-plugin` to v4 and running `npm install` works fine as well, both using `npm@8.5.5`. This is an issue with your package manager or your project.

**Comment by ThinkRealize** [comment]
@SimenB  Thanks。The problem has been solved。
