### ISSUE TITLE
Multiple assets

### ISSUE THREAD

**Issue by RyanEwen** [SimenB/add-asset-html-webpack-plugin#4]
Is there any way to specify multiple assets? My project uses 2 DLLs.

It seems that using the plugin twice causes an error.

**Comment by RyanEwen** [comment]
Found the issue and opened a [PR](https://github.com/SimenB/add-asset-html-webpack-plugin/pull/5) :)

**Comment by RyanEwen** [comment]
Relevant feature request: the ability to specify multiple assets at a time would be nice.

**Comment by SimenB** [comment]
Is this issue closed?

> Relevant feature request: the ability to specify multiple assets at a time would be nice.

If still relevant, could you create a separate issue?

**Comment by SimenB** [comment]
@RyanEwen Any ideas about what API would be best? I'm thinking the same as now, but passed as an array instead of single object. Then I can just wrap the object in an array if that's what's passed in

**Comment by RyanEwen** [comment]
This can be closed :)

I was thinking the same thing implementation-wise. I'm not sure about the order, though, and in my use case the html webpack plugin option 'chunksSortMode' is 'dependency' and that seems to work well for me. But maybe that was just luck?
