### ISSUE TITLE
Using this plugin with webpack-dev-middleware

### ISSUE THREAD

**Issue by dmeenhuis** [SimenB/add-asset-html-webpack-plugin#47]
Hi,

First of all, thanks for this plugin, it solves a problem I was having before when trying to use DLL's and HtmlWebpackPlugin.

I do however have a question with regards to the usage in development mode. My local dev server is started with ``express`` and uses ``webpack-dev-middleware`` and ``webpack-hot-middleware``.

This setup is working just fine, combined with this plugin, but the thing I'm running into is that webpack still seems to build the vendor DLL bundle whenever a hot reload occurs. I was hoping to reduce the incremental build times by bundling the vendor code into a separate DLL.

The bit below is the output from one of my incremental builds. As you can see, it still includes ``vendor.js``, which increases the incremental build time significantly.

```code
webpack built 6ad0a0db186792c82b36 in 5516ms
Version: webpack 2.2.0-rc.3
Time: 5516ms
                                Asset       Size  Chunks                    Chunk Names
           [...omitted for brevity]
                     main.9b0addb8.js    2.65 MB      11  [emitted]  [big]  main
11.4200948c64c885ebaee9.hot-update.js    3.54 kB      11  [emitted]         main
 4200948c64c885ebaee9.hot-update.json   44 bytes          [emitted]
                            vendor.js     3.6 MB          [emitted]  [big]
                           index.html  492 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.45 MB       0
webpack: bundle is now VALID.
```

My ``webpack.confg.js`` plugin section is as following:

```javascript
  new webpack.DllReferencePlugin({
    context: path.join(__dirname, 'src'),
    manifest: require(path.join(__dirname, './vendor/vendor-manifest.json'))
  }),
  new HtmlWebpackPlugin({
    template: path.resolve(__dirname, 'src', 'index.html'),
    inject: 'body',
    minify: production && {
      collapseWhitespace: true
    }
  }),
  new AddAssetHtmlPlugin({
    filepath: require.resolve('./build/vendor.js'),
    includeSourcemap: false,
    hash: production,
  }),
```

Is this the intended behaviour or am I perhaps missing something here?

**Comment by SimenB** [comment]
Hi @dmeenhuis! Sorry about the slow response...

It is expected, as the file is written to disk (or in-mem). No processing on it is made by Webpack though, it's just written out. The saving is that if Webpack hits a dependency it knows is in a DLL, it doesn't process that one, just links it to the existing DLL.

Does that make sense or should I try to rephrase? 😄
