### ISSUE TITLE
could add-asset-html-webpack-plugin specify entry ?

### ISSUE THREAD

**Issue by superpig** [SimenB/add-asset-html-webpack-plugin#61]
<img width="397" alt="screen shot 2017-04-21 at 5 13 27 pm" src="https://cloud.githubusercontent.com/assets/5066518/25271189/df62c628-26b5-11e7-8730-2f58533a7af0.png">

I create a vendor bundle with `webpack.DllPlugin`，and i have multiple entry in my project，i only want to insert vendor  bundle into one entry，but `add-asset-html-webpack-plugin`  inserts vendor bundle into all entries，is there any other way ?

**Comment by SimenB** [comment]
That's not currently possible, no. That sounds useful though, so if you could send a PR, I'll gladly help you through it 😄

**Comment by superpig** [comment]
I have found [html-webpack-include-assets-plugin](https://github.com/jharris4/html-webpack-include-assets-plugin) and [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin), which could solve my problem。

**Comment by SimenB** [comment]
Huh, html-webpack-include-assets-plugin looks similar to this project, should probably combine our efforts! Thanks for pointing it out 😄 

Great if it solved your problem, though!

**Comment by jharris4** [comment]
Ha! yes, these plugins are very similar! The `files` option of https://github.com/jharris4/html-webpack-include-assets-plugin is designed to solve the feature requested by this issue.

We should indeed probably combine our efforts :-)

**Comment by SimenB** [comment]
Released in 2.0.0
