### ISSUE TITLE
Error in No filepath defined

### ISSUE THREAD

**Issue by tfmertz** [SimenB/add-asset-html-webpack-plugin#65]
I'm running into an error when using this plugin in a dll webpack development build. I'm using:
* Webpack 2.5.0
* HtmlWebpackPlugin 2.28.0
* AddAssetHtmlWebpackPlugin 2.0.1

When I remove my AddAssetHtmlWebpackPlugin from the config it builds fine.

My HtmlWebpackPlugin config is
```
new HtmlWebpackPlugin({
  template: path.join(PATHS.app, 'index.html'),
  inject: 'body'
}),
```

and my AddAssetHtmlWebpackPlugin config is

```
new AddAssetHtmlPlugin({
  filename: require.resolve('./dist/dll.vendor.js')
}),
```

Am I missing something? Thanks!

**Comment by jharris4** [comment]
Did you try debugging what `require.resolve` is returning? It looks like you might have a relative path issue causing it to return undefined...

Maybe try with `require.resolve('./dll.vendor.js')` ?

**Comment by SimenB** [comment]
@tfmertz Typo in options, you should use `filepath`, not `filename`.

197540634d42781542218ed8d3a1af1eae269f76

**Comment by SimenB** [comment]
@jharris4 `require.resolve` throws if it can't find the file, which is why I recommended that in the docs 😄 

```sh-session
$ node -p "require.resolve('blahdebla')"
module.js:471
    throw err;
    ^

Error: Cannot find module 'blahdebla'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at [eval]:1:9
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:358:29)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
```

**Comment by tfmertz** [comment]
Thanks @SimenB ! I woke up in the middle of the night with this realization. Doh! I'm not out of the woods yet though. Once that error was fixed now I have a
```
Error: HtmlWebpackPlugin: could not load file /usr/src/app/dist/dll.vendor.js.  map
```
The spacing makes it read weird, but is this looking for a .map file? The `add-asset-html-webpack-plugin` is included in the stack trace, but maybe this is an HtmlWebpackPlugin issue. (or most likely user error)

**Comment by SimenB** [comment]
Hmm, All I do is `https://github.com/SimenB/add-asset-html-webpack-plugin/blob/ff187d9471343f16eafffa906a934785523ea2d8/src/addAllAssetsToCompilation.js#L71`, so the spacing is indeed weird.

Do you have a sourcemap? If not, you have to pass `sourcemap: false` as argument

**Comment by tfmertz** [comment]
Ah, that's what it was. Thanks for the clarification.
