### ISSUE TITLE
Error: HtmlWebpackPlugin could not load file xxx.js.map

### ISSUE THREAD

**Issue by ChrisShen93** [SimenB/add-asset-html-webpack-plugin#67]
Once I use add-asset-html-webpack-plugin in my project I got the Error

ERROR in   Error: HtmlWebpackPlugin: could not load file E:\myPath\static\dll\charts.dll.js.map

Please tell me how to fixed it

I add the config like this:
```javascript
module.exports.plugins.push(new HtmlWebpackPlugin(conf), new AddAssetHtmlPlugin([
    {filepath: require.resolve('../static/dll/vendor.dll.js')},
    {filepath: require.resolve('../static/dll/charts.dll.js')}
  ]));
```

OS: windows 10
npm: 3.10.10
node: 6.10.2
webpack: 2.6.1

**Comment by ChrisShen93** [comment]
Fixed the problem
just add **includeSourcemap** to the configuration

However, have you tested the multi-entries project?
In my multi-pages project, for example, 4 entries, add-asset-html-webpack-plugin will add my dll.js 4 times to each entry.html

**Comment by SimenB** [comment]
Might make sense to flip the default, seems like a lot of people trip up on it

**Comment by EvanBurbidge** [comment]
@ChrisShen93 did you add the config to HtmlWebpackPlugin or AddAsset?

**Comment by ChrisShen93** [comment]
@EvanBurbidge 
Yes for sure
