### ISSUE TITLE
what  filter config

### ISSUE THREAD

**Issue by zsl99a** [SimenB/add-asset-html-webpack-plugin#73]
new AddAssetHtmlPlugin({
      filter: 'what config?',
      filepath: require.resolve(`./dist/${require('./dist/libs_manifest.json').name}.dll.js`),
    }),

**Comment by SimenB** [comment]
What do you mean? You you explain what parts of the docs are unsatisfactory?

**Comment by zsl99a** [comment]
I think not all Htmlwebpackpin configured pages need to load this DLL, and I try to pass the name of the DLL as a parameter to the filter, but no

**Comment by zsl99a** [comment]
I think not all Htmlwebpackpin configured pages need to load this DLL, and I try to pass the name of the DLL as a parameter to the filter, but no

**Comment by zsl99a** [comment]
对了, 我还同时尝试配置了htmlwebpackpin的chunks属性

**Comment by zsl99a** [comment]
By the same time, I also tried to configure the Htmlwebpackpin chunks property

**Comment by SimenB** [comment]
You pass the name of the html file you want to include the dll in, not the other way around. Does that make sense?

**Comment by karijkangas** [comment]
I think the option is 'files', not 'filter' as suggested by the document. At least that seems to work for me :-)

**Comment by SimenB** [comment]
Bah, stupid typo. Thanks for the eagle eyes @karijkangas!
