### ISSUE TITLE
ERROR in   Error: HtmlWebpackPlugin: could not load file C:\mypath\public\js\index.js.map

### ISSUE THREAD

**Issue by radiance8888** [SimenB/add-asset-html-webpack-plugin#86]
I'm geting the above error when i'm trying to add the script links.
This is the part where i'm including html plugin in webpack.config.js

    new AddAssetHtmlPlugin({
        filepath: require.resolve('./public/js/index.js')
    }),
    new AddAssetHtmlPlugin({
        filepath: require.resolve('./public/js/getUrl.js')
    }),

    new HtmlWebpackPlugin({
        title: 'Monitoring Status',
        minify: {
            collapseWhitespace: true
        },
        template: 'views/index.ejs', // Load a custom template (ejs by default see the FAQ for details),
        chunksSortMode: 'none'

    }),

    new HtmlWebpackExternalsPlugin({
        externals: [{
            module: 'bootstrap-table',
            entry: ['dist/bootstrap-table.min.css', 'dist/bootstrap-table.min.js']
        }, ],
    }),
    new HtmlWebpackExternalsPlugin({
        externals: [{
            module: 'bootstrap',
            entry: ['dist/css/bootstrap.min.css', 'dist/js/bootstrap.min.js']
        }, ],
    }),

    new HtmlWebpackExternalsPlugin({
        externals: [{
            module: 'jquery',
            entry: 'dist/jquery.min.js',
            global: 'jQuery',
        }, ],
    })
This is how it is generating the script in index.html now ,without adding AddAssetHtmlPlugin.
This is the links which are in the generated html file

    <script type="text/javascript" src="vendor/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="vendor/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script type="text/javascript" src="app.bundle.js"></script>
    <script type="text/javascript" src="bootstrap.bundle.js"></script>
    <script type="text/javascript" src="dist/jquery.min.js"></script>

So now i want to add the below script path too right after the above.

    <script src="js/index.js"></script>
    <script src="js/getUrl.js"></script>

I'm trying to add the scripts in  the generated index file  like below

     new AddAssetHtmlPlugin({
        filepath: require.resolve('./public/js/index.js')
    },
    {
        filepath: require.resolve('./public/js/getUrl.js')
    }
    ),
   but it is throwing ERROR in   Error: HtmlWebpackPlugin: could not load file C:\mypath\public\js\index.js.map

Is anything is wrong in my code? Is it the way or should i change? Why am i getting this error?

**Comment by SimenB** [comment]
You need to disable sourcemaps. https://github.com/SimenB/add-asset-html-webpack-plugin/blob/master/README.md#includesourcemap
