### ISSUE TITLE
Option  includeSourcemap

### ISSUE THREAD

**Issue by showbestriven** [SimenB/add-asset-html-webpack-plugin#87]
if I use many files  filePath 
such as 
    new AddAssetHtmlPlugin({
        filepath: path.resolve(__dirname, '..', './static/js/*.dll.js'),
        filepath: path.resolve(__dirname, '..', './static/tinymce/tinymce.min.js'),
    })
could I only let tinymce.min.js 's   includeSourcemap: false ,
   *.dll.js is true

**Comment by SimenB** [comment]
You can't have multiple `filepath` in the same object.

```js
new AddAssetHtmlPlugin([
  { filepath: path.resolve(__dirname, '..', './static/js/*.dll.js') },
  { filepath: path.resolve(__dirname, '..', './static/tinymce/tinymce.min.js'), includeSourcemap: false },
])
```

That looks more correct. Does it work for you?

**Comment by showbestriven** [comment]
Thanks, I‘ll  try it!

**Comment by showbestriven** [comment]
it has insert in index.html 
but 

if I write `<script src=<%= htmlWebpackPlugin.options.path %>/static/tinymce/tinymce.min.js></script>` in  index.html , it could be worked

**Comment by showbestriven** [comment]
it has insert in index.html
but it can't find another moudle, it's worng  
![image](https://user-images.githubusercontent.com/25165547/32428751-5c828448-c302-11e7-9e08-7ccc2e90a818.png)

if I write `<script src=<%= htmlWebpackPlugin.options.path %>/static/tinymce/tinymce.min.js></script>` in index.html , it could be worked

**Comment by showbestriven** [comment]
![image](https://user-images.githubusercontent.com/25165547/32428988-87fe0fba-c303-11e7-91ea-bc1c6a90c9d4.png)
It has be inserted,  but it can't  find another file in the router
![image](https://user-images.githubusercontent.com/25165547/32429023-be9dd9c4-c303-11e7-8f7e-66829c11b572.png)
If I write `<script src=<%= htmlWebpackPlugin.options.path %>/static/tinymce/tinymce.min.js></script>`, use this way,the tinymce can work

**Comment by hmrasi** [comment]
How can i include my dll files created using JAVASCRIPT in the HTML page?

**Comment by SimenB** [comment]
This is an old issue, please open up a new one if you're still having issues
